### PR TITLE
icons Added in footer

### LINKED ISSUE #260: [Feature]: Added the section Name and Icons
### Description

In the 2nd section I added the heading name as STEPS TO LEARN and in 3rd section i added the heading name as OUR COURSES

and also I added icons in the footer section links

these gives new good look to the page

### Screenshots

before 
Screenshot (1746)

Screenshot (1747)

after

Screenshot (1748)

Screenshot (1749)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSOC'24 contributor

### PR DESCRIPTION
**Pull request by SadafKausar2025**
Hi @JAYESHBATRA 

## Related Issue  #260

Closes #260

## Description
Added Section Name and icons in the Footer 

## Screenshots (if applicable)
original 
Screenshot (1746)
Screenshot (1747)

updated

Screenshot (1748)
Screenshot (1749)

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
hi @JAYESH-BATRA 
I have resolved the conflict .
can you please merge this PR?

**Comment by JAYESHBATRA** [comment]
@SadafKausar2025 Kindly resolve the conflicts and raise a new PR .

**Comment by SadafKausar2025** [comment]
hello @JAYESHBATRA 
please reopen the PR i will resolve the conflicts here

**Comment by SadafKausar2025** [comment]
Hii @JAYESHBATRA 
Now I resolved the conflicts it's ok now

**Comment by JAYESHBATRA** [comment]
@SadafKausar2025
Kindly note that the changes you have made are causing the size of the navbar image to change, which is undesirable. Please fix this issue and then raise a PR.
image

**Comment by SadafKausar2025** [comment]
ok I will fixed it and again raise PR

**Pull request closed without merging**
