### PR TITLE
Issue No #182 [BUG FIXED] In the footer section, the copyright year should be dynamically generated instead of being statically hardcoded.

### LINKED ISSUE #182: [BUG] In the footer section, the copyright year should be dynamically generated instead of being statically hardcoded.
### Description

@JAYESH-BATRA Right now, the copyright year is written manually, which means someone has to change it whenever a new year begins. However, with just a few lines of code in JavaScript, we can make it automatic. This means that the copyright year will always be up-to-date without anyone having to change it manually. For example, if the current year is 2024, the copyright section will show 2024. And when the year changes to 2025, the copyright section will automatically update to 2025.

### Screenshots

Screenshot 2024-02-12 022440
Screenshot 2024-02-12 022249

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor
- [ ] I am an IWOC 2.0 contributor

### PR DESCRIPTION
**Pull request by gauravsingh1281**
## Related Issue

Closes #182 

## Description

In this Pull request, I have added the dynamically generated copyright year in the footer section of the site by replacing the statically hardcoded copyright year value. 

## Checklist 

- [x] My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x] My changes have not introduced any new warnings.
- [x] I have conducted a self-review of my code.

### CODE REVIEW

**Comment by gauravsingh1281** [comment]
@JAYESHBATRA please add Swoc 24 label.

**Comment by gauravsingh1281** [comment]
@JAYESHBATRA Please add the SWOC24 label.

**Comment by JAYESHBATRA** [comment]
It is already added in the issue @gauravsingh1281

**Comment by gauravsingh1281** [comment]
> It is already added in the issue @gauravsingh1281

but Quine will track PR with the SWOC24 label only not issue

**Pull request merged**
