### PR TITLE
feat: Contact Page

### LINKED ISSUE #31: [Feature] There should be a new section of contact us.
### Description

There should be a form which contains name , email and queries to contact us.

Like below example 

### Screenshots

Screenshot (42)

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'23 contributor

### LINKED ISSUE #167: [Feature] Add a contact page
### Description

This website needs a contact us page so that one can contact to the owner regarding any issue. 

### Screenshots

_No response_

### Checklist

- [X] I have starred the repository
- [X] I have checked the existing issues
- [X] I have read the discussion tab thoroughly and got the project idea 
- [X] I am willing to work on this issue (optional)
- [ ] I am a SWOC'24 contributor
- [X] I am an IWOC 2.0 contributor

### PR DESCRIPTION
**Pull request by Gokilp**
fixed the add contact page 

Closes #31 

Description

contact page is not properly work i fixed issue and responsive ui create a new contact page now will work contact page properly and responsive ui

Screenshots (if applicable)
Original	Updated
|
image

|
image
|

Original	Updated
|
image
|
image
|

Checklist
- [x]  My code adheres to the established style guidelines of the project.
- [x] I have included comments in areas that may be difficult to understand.
- [x]  My changes have not introduced any new warnings.
- [x]  I have conducted a self-review of my code.

### CODE REVIEW

**Comment by Gokilp** [comment]
@JAYESHBATRA  please review my pr 

im confused about make pr multiple every failed it  help me

**Comment by Gokilp** [comment]
kindly review my pr

**Comment by JAYESHBATRA** [comment]
@Gokilp A Contact Us section is required on home page itself and not a separate page. Kindly raise a new PR to fix the issues.

**Comment by Gokilp** [comment]
I'm make new pr

**Comment by Gokilp** [comment]
Can you clarify your requirement  about page  Contact page @JAYESHBATRA

**Pull request closed without merging**
